### ISSUE TITLE
Cannot update to secret_agent v0.8.3

### ISSUE THREAD

**Issue by jgallinari** [ahamez/secret_agent#88]
Salut Alex,

It seems as if we cannot update secret_agent to v0.8.3, we're stuck to v0.8.2

## How to reproduce

```bash
❯ mix new hello
❯ cd hello
```

Then update mix.exs to use
```elixir
  defp deps do
    [
      {:secret_agent, "~> 0.8"}
    ]
  end
```

```bash

❯ mix deps.get
Resolving Hex dependencies...
Resolution completed in 0.032s
New:
  nimble_options 1.1.1
  secret_agent 0.8.2
  secrets_watcher_file_system 0.2.10
  telemetry 1.3.0
* Getting secret_agent (Hex package)
* Getting nimble_options (Hex package)
* Getting secrets_watcher_file_system (Hex package)
* Getting telemetry (Hex package)
 ```
🤔 

```bash
❯ mix deps.update secret_agent
Resolving Hex dependencies...
Resolution completed in 0.007s
Unchanged:
  nimble_options 1.1.1
  secret_agent 0.8.2
  secrets_watcher_file_system 0.2.10
  telemetry 1.3.0
```

I found out about that while updating to Elixir v1.17, which caused a warning to appear in my tests due to `secrets_watcher_file_system`, which you do not use anymore...

Thanks,
Jerome

**Comment by ahamez** [comment]
👋
I simply forgot to publish version 0.8.3…😅
I took the opportunity to release (and publish!) a version 0.8.4 (with updated dependencies).
Tell me if it fixes the issue for you!

**Comment by jgallinari** [comment]
Gé-nial!
It works plenty.
Thanks!
